name: Backend Continuous Integration

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
      
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install pipenv dependency
        run: | 
          pip install pipenv
          pip install flake8
      - name: Install dependency, run test lint, run test
        run: | 
          cd starter/backend
          pipenv install 
          pipenv run lint
          pipenv run test
  build-docker-backend:
      needs: [backend-test]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Build, Build docker
          run: | 
             cd starter/backend
             docker build --tag=mp-backend:latest .